version: '3'

services:
  frontend:
    build: ../packages/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ../node_modules:/app/node_modules
      - ../packages/frontend:/app
    env_file:
      - .env.prod

  backend:
    build: ../packages/backend
    ports:
      - "443:443"
    depends_on:
      - db
    volumes:
      - ../node_modules:/app/node_modules
      - ../packages/backend:/app
    env_file:
      - .env.prod

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.prod