version: '3.8'

services:
  backend:
    build:
      context: ./docker/prod
      dockerfile: Dockerfile
    container_name: backend-prod
    ports:
      - "443:443"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://<user>:<password>@<neon_host>:<port>/<dbname>?schema=public  # Neon connection string
    depends_on:
      - postgres
    command: ["yarn", "workspace", "@scope/backend", "start"]

  frontend:
    build:
      context: ./docker/prod
      dockerfile: Dockerfile
    container_name: frontend-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    command: ["yarn", "workspace", "@scope/frontend", "start"]

  postgres:
    image: postgres:13
    container_name: postgres-prod
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
